name: main-build
on:
  # Triggers the workflow on push or pull request events but only for the v1.1beta_helm_pkg_update_lber_ay branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - env:
          L_ARCH: linux
        run: |
          mkdir ./lib;cd ./lib
          wget https://raw.githubusercontent.com/LIBRA-Release/libra/v0.1.0-reiwa/lib/${L_ARCH}/crypto.h
          wget https://raw.githubusercontent.com/LIBRA-Release/libra/v0.1.0-reiwa/lib/${L_ARCH}/crypto.so
          cd -
          RUSTFLAGS="-C link-args=-Wl,$(pwd)/lib/crypto.so" cargo build -vv
          tree ./          
        #continue-on-error: true
      #- name: post-checker
      #  run: |
      #    tree ./
          
           
